#!/usr/bin/env bash
# run-agent.sh — Execute an AI agent inside a worktree (called by spawn-agent.sh inside tmux)
# Usage: run-agent.sh <task_id> <task_desc> <agent_type> <worktree_dir> <branch_name>

set -euo pipefail

TASK_ID="$1"
TASK_DESC="$2"
AGENT_TYPE="$3"
WORKTREE_DIR="$4"
BRANCH_NAME="$5"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TASKS_FILE="$SCRIPT_DIR/active-tasks.json"
LOG_FILE="$WORKTREE_DIR/.openclaw-agent.log"

# --- Helper: update task field in active-tasks.json ---
update_task() {
  local field="$1" value="$2"
  local tmp=$(mktemp)
  jq --arg id "$TASK_ID" --arg f "$field" --arg v "$value" \
    '(.[] | select(.id == $id))[$f] = $v | (.[] | select(.id == $id)).updated_at = (now | strftime("%Y-%m-%dT%H:%M:%SZ"))' \
    "$TASKS_FILE" > "$tmp" && mv "$tmp" "$TASKS_FILE"
}

log() {
  echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log "=== OpenClaw Agent Starting ==="
log "Task:   $TASK_DESC"
log "Agent:  $AGENT_TYPE"
log "Branch: $BRANCH_NAME"
log "Dir:    $WORKTREE_DIR"

cd "$WORKTREE_DIR"

# --- Build the prompt for the agent ---
AGENT_PROMPT="You are working on a coding task in a git repository.

TASK: $TASK_DESC

INSTRUCTIONS:
- Work in the current directory (already on branch '$BRANCH_NAME')
- Make the necessary code changes to complete the task
- Write clean, well-tested code
- Commit your changes with a clear commit message
- Do NOT push or create PRs — that will be handled automatically after you finish

Current branch: $BRANCH_NAME
Working directory: $WORKTREE_DIR"

# --- Run the agent ---
log "🤖 Starting $AGENT_TYPE agent..."

EXIT_CODE=0
if [[ "$AGENT_TYPE" == "codex" ]]; then
  # OpenAI Codex CLI
  if command -v codex &>/dev/null; then
    codex exec -s danger-full-access -C "$WORKTREE_DIR" "$AGENT_PROMPT" 2>&1 | tee -a "$LOG_FILE" || EXIT_CODE=$?
  else
    log "❌ codex CLI not found. Install: npm i -g @openai/codex"
    update_task "status" "failed"
    exit 1
  fi

elif [[ "$AGENT_TYPE" == "claude" ]]; then
  # Anthropic Claude Code CLI
  if command -v claude &>/dev/null; then
    claude -p --dangerously-skip-permissions "$AGENT_PROMPT" 2>&1 | tee -a "$LOG_FILE" || EXIT_CODE=$?
  else
    log "❌ claude CLI not found. Install: npm i -g @anthropic-ai/claude-code"
    update_task "status" "failed"
    exit 1
  fi
fi

# --- Check if agent made any changes ---
if [[ $EXIT_CODE -ne 0 ]]; then
  log "❌ Agent exited with code $EXIT_CODE"
  update_task "status" "failed"
  exit $EXIT_CODE
fi

# Check for uncommitted changes and commit them
if [[ -n "$(git status --porcelain)" ]]; then
  log "📦 Committing remaining changes..."
  git add -A
  git commit -m "openclaw($TASK_ID): $TASK_DESC" --no-verify || true
fi

# Check if we have any new commits vs origin
COMMIT_COUNT=$(git rev-list --count "origin/$(git -C "$SCRIPT_DIR/.." symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo main)..HEAD" 2>/dev/null || echo "0")

if [[ "$COMMIT_COUNT" -eq 0 ]]; then
  log "⚠️  Agent made no commits. Marking as failed."
  update_task "status" "failed"
  exit 1
fi

log "📤 Pushing branch $BRANCH_NAME..."
git push origin "$BRANCH_NAME" 2>&1 | tee -a "$LOG_FILE"

# --- Create PR via gh CLI ---
if command -v gh &>/dev/null; then
  log "🔀 Creating Pull Request..."
  PR_URL=$(gh pr create \
    --title "🤖 [$AGENT_TYPE] $TASK_DESC" \
    --body "## Auto-generated by OpenClaw

**Task:** $TASK_DESC
**Agent:** $AGENT_TYPE
**Task ID:** $TASK_ID
**Branch:** $BRANCH_NAME

---
*This PR was automatically created by an AI coding agent. Please review carefully.*" \
    --head "$BRANCH_NAME" 2>&1) || {
    log "⚠️  Failed to create PR: $PR_URL"
    update_task "status" "push-done"
    exit 0
  }

  PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$' || echo "")
  log "✅ PR created: $PR_URL"

  update_task "status" "pr-open"
  update_task "pr_url" "$PR_URL"
  [[ -n "$PR_NUMBER" ]] && update_task "pr_number" "$PR_NUMBER"
else
  log "⚠️  gh CLI not found — skipping PR creation. Push done."
  update_task "status" "push-done"
fi

log "=== Agent Complete ==="
